import { ITEM_COUNT } from "../client/src/app/constants";
import { ObjectType } from "./avatars-info";
import { GameObject } from "./interfaces/game-object";

export const gameObjects: GameObject[] = [
    {
        id: ObjectType.Trident,
        name: 'ITEMS.TRIDENT.NAME',
        image: './assets/images/objects/poseidon-trident.jpg',
        description: 'ITEMS.TRIDENT.DESCRIPTION',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Armor,
        name: 'ITEMS.ARMOR.NAME',
        image: './assets/images/objects/armor-of-achilles.jpg',
        description: 'ITEMS.ARMOR.DESCRIPTION',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Sandal,
        name: 'ITEMS.SANDAL.NAME',
        image: './assets/images/objects/winged-sandals.jpg',
        description: 'ITEMS.SANDAL.DESCRIPTION',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Lightning,
        name: 'ITEMS.LIGHTNING.NAME',
        image: './assets/images/objects/zeus-lightning.jpg',
        description: 'ITEMS.LIGHTNING.DESCRIPTION',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Xiphos,
        name: 'ITEMS.XIPHOS.NAME',
        image: './assets/images/objects/xiphos.jpg',
        description: 'ITEMS.XIPHOS.DESCRIPTION',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Kunee,
        name: 'ITEMS.KUNEE.NAME',
        image: './assets/images/objects/helm-of-darkness.jpg',
        description: 'ITEMS.KUNEE.DESCRIPTION',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Random,
        name: 'ITEMS.RANDOM.NAME',
        image: './assets/images/objects/dice.jpg',
        description: 'ITEMS.RANDOM.DESCRIPTION',
        count: -1,
    },
    {
        id: ObjectType.Spawn,
        name: 'ITEMS.SPAWN.NAME',
        image: './assets/images/objects/tree.jpg',
        description: 'ITEMS.SPAWN.DESCRIPTION',
        count: -1,
    },
    {
        id: ObjectType.Flag,
        name: 'ITEMS.FLAG.NAME',
        image: './assets/images/objects/flag.jpg',
        description: 'ITEMS.FLAG.DESCRIPTION',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Hestia,
        name: "Hestia",
        image: "./assets/images/characters/Hestia.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Zeus,
        name: "Zeus",
        image: "./assets/images/characters/Zeus.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Hera,
        name: "Hera",
        image: "./assets/images/characters/Hera.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Poseidon,
        name: "Poseidon",
        image: "./assets/images/characters/Poseidon.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Artemis,
        name: "Artemis",
        image: "./assets/images/characters/Artemis.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Demeter,
        name: "Demeter",
        image: "./assets/images/characters/Demeter.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Hermes,
        name: "Hermes",
        image: "./assets/images/characters/Hermes.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Athena,
        name: "Athena",
        image: "./assets/images/characters/Athena.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Hephaestus,
        name: "Hephaestus",
        image: "./assets/images/characters/Hephaestus.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Apollo,
        name: "Apollo",
        image: "./assets/images/characters/Apollo.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Ares,
        name: "Ares",
        image: "./assets/images/characters/Ares.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Aphrodite,
        name: "Aphrodite",
        image: "./assets/images/characters/Aphrodite.webp",
        description: "Photo de Hestia",
        count: -1,
    },
    {
        id: ObjectType.Dionysus,
        name: "Dionysus",
        image: "./assets/images/characters/Dionysus.webp",
        description: "Photo de Dionysus",
        count: -1,
    },
    {
        id: ObjectType.Hades,
        name: "Hades",
        image: "./assets/images/characters/Hades.webp",
        description: "Photo de Hades",
        count: -1,
    },
    {
        id: ObjectType.Persephone,
        name: "Persephone",
        image: "./assets/images/characters/Persephone.webp",
        description: "Photo de Persephone",
        count: -1,
    },
];
